deploy_docker:
  script:
    - go mod init
    - go mod tidy
    - docker stop cryptowowserver || true && docker rm cryptowowserver || true
    - docker build -t cryptowowserver .
    - docker run --network general_bridge -d --name cryptowowserver -p 4300:4300 cryptowowserver