version: "3.3"

services:
    cache:
        image: redis:5.0.7
        container_name: redis
        ports:
            - 6379:6379
        command: redis-server --save 20 1 --loglevel warning --requirepass 021021ali
        volumes:
            - ./cache:/data
    api:
        container_name: api
        build: .
        ports:
            - 4300:4300
        depends_on:
            - cache
        links:
            - cache
networks:
    default:
        external:
            name: general_bridge